# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Accuracy
#'
#' This function computes the accuracy of predictions (%correct).
#'
#' @param actual A vector containing the observed class of a point
#' @param predicted A vector containing the predicted class or probability
#' of class membership at a point
#' @param threshold Optional parameter which is the probability threshold
#' at which a point is classified as a member of class 1.
accuracy <- function(actual, predicted, threshold = 0.5) {
    .Call('airR_accuracy', PACKAGE = 'airR', actual, predicted, threshold)
}

#' Mean squared error
#'
#' This function will calculate the mean squared error between two vectors.
#'
#' @param actual A vector containing the observed value of a point
#' @param predicted A vector containing the predicted value at a point
NULL

#' Squared error
#'
#' This function will calculate the element-wise squared error between two vectors
#'
#' @param actual A vector containing the observed value of a point
#' @param predicted A vector containing the predicted value at a point
#'
squared_error <- function(actual, predicted) {
    .Call('airR_squared_error', PACKAGE = 'airR', actual, predicted)
}

mean_sq_error <- function(actual, predicted) {
    .Call('airR_mean_sq_error', PACKAGE = 'airR', actual, predicted)
}

#' Root mean squared error
#'
#' This function will calculate the root mean squared error between two vectors.
#'
#' @param actual A vector containing the observed value of a point
#' @param predicted A vector containing the predicted value at a point
rmse <- function(actual, predicted) {
    .Call('airR_rmse', PACKAGE = 'airR', actual, predicted)
}

#' Absolute error
#'
#' This function will calculate the element-wise absolute error between two vectors.
#'
#' @param actual A vector containing the observed value of a point
#' @param predicted A vector containing the predicted value at a point
absolute_error <- function(actual, predicted) {
    .Call('airR_absolute_error', PACKAGE = 'airR', actual, predicted)
}

#' Mean absolute error
#'
#' This function will calculate the mean absolute error between two vectors.
#'
#' @param actual A vector containing the observed value of a point
#' @param predicted A vector containing the predicted value at a point
mean_abs_error <- function(actual, predicted) {
    .Call('airR_mean_abs_error', PACKAGE = 'airR', actual, predicted)
}

#' Median absolute error
#'
#' This function will calculate the median absolute error between two vectors.
#'
#' @param actual A vector containing the observed value of a point
#' @param predicted A vector containing the predicted value at a point
median_abs_error <- function(actual, predicted) {
    .Call('airR_median_abs_error', PACKAGE = 'airR', actual, predicted)
}

#' R2 score
#'
#' This function will calculate the r2 score between two vectors.
#'
#' @param actual A vector containing the observed value of a point
#' @param predicted A vector containing the predicted value at a point
r2_score <- function(actual, predicted) {
    .Call('airR_r2_score', PACKAGE = 'airR', actual, predicted)
}

